import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const aileron = localFont({
    variable: "--font-aileron",
    src: [
        {
            path: "./fonts/Aileron-Regular.otf",
            weight: "400",
            style: "normal",
        },
        {
            path: "./fonts/Aileron-Bold.otf",
            weight: "700",
            style: "bold",
        },
        {
            path: "./fonts/Aileron-Italic.otf",
            weight: "400",
            style: "italic",
        },
        {
            path: "./fonts/Aileron-BoldItalic.otf",
            weight: "700",
            style: "italic",
        },
        {
            path: "./fonts/Aileron-UltraLight.otf",
            weight: "300",
            style: "light",
        },
        {
            path: "./fonts/Aileron-UltraLightItalic.otf",
            weight: "300",
            style: "italic",
        },
    ],
});

const cooper = localFont({
    variable: "--font-cooper",
    src: [
        {
            path: "./fonts/Cooper-Regular.otf",
            weight: "400",
            style: "normal",
        },
        {
            path: "./fonts/Cooper-Bold.otf",
            weight: "700",
            style: "bold",
        },
        {
            path: "./fonts/Cooper-Italic.otf",
            weight: "400",
            style: "italic",
        },
        {
            path: "./fonts/Cooper-BoldItalic.otf",
            weight: "700",
            style: "italic",
        },
    ],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${aileron.variable} ${cooper.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
